dassssshers/nilts

packages/nilts/lib/src/lints/use_media_query_xxx_of.dart

Update `use_media_query_xxx_of` url to README on this repo.

docs: update use_media_query_xxx_of url

---

packages/nilts/lib/src/dart_version.dart
packages/nilts/lib/src/lints/use_media_query_xxx_of.dart
packages/nilts/pubspec.yaml

Support dart version >= 2.19.0.

build: wide support dart version

---

.github/FUNDING.yml

build: sponsor config

---

packages/nilts/lib/src/lints/use_media_query_xxx_of.dart
packages/nilts_test/test/lints/use_media_query_xxx_of.dart

Refactor source range replacement with node offset and length.

refactor: source range replacement

---

pubspec.yaml

bump up melos 3.1.1
https://github.com/invertase/melos/blob/main/CHANGELOG.md

upgrade: update melos

---

packages/nilts/README.md
packages/nilts/lib/nilts.dart
packages/nilts/lib/src/change_priority.dart
packages/nilts/lib/src/lints/flaky_tests_with_set_up_all.dart
packages/nilts_test/test/lints/flaky_tests_with_set_up_all.dart

add `flaky_tests_with_set_up_all` rule.

feat: flaky_tests_with_set_up_all

---

packages/nilts/lib/src/lints/unnecessary_rebuilds_from_media_query.dart

Update Dart Docs for UnnecessaryRebuildsFromMediaQuery.

docs: update dart docs for UnnecessaryRebuildsFromMediaQuery

---

examples/nilts_example/pubspec.yaml
packages/nilts/pubspec.yaml
packages/nilts_test/pubspec.yaml

Update
- [analyzer](https://pub.dev/packages/analyzer)
- [custom_lint](https://pub.dev/packages/custom_lint_builder)
- [custom_lint_builder](https://pub.dev/packages/custom_lint)

upgrade: update analyzer and custom_lint

---

examples/nilts_example/pubspec.yaml
packages/nilts/pubspec.yaml
packages/nilts_test/pubspec.yaml

- wide version support for [analyzer](https://pub.dev/packages/analyzer)
- bump up [custom_lint](https://pub.dev/packages/custom_lint)

upgrade: update dependencies

---

packages/nilts/README.md
packages/nilts/lib/src/lints/unnecessary_rebuilds_from_media_query.dart

docs: update unnecessary_rebuilds_from_media_query notes

---

packages/nilts/README.md
packages/nilts/lib/nilts.dart
packages/nilts/lib/src/change_priority.dart
packages/nilts/lib/src/lints/fixed_text_scale_factor_rich_text.dart
packages/nilts/lib/src/lints/flaky_tests_with_set_up_all.dart
packages/nilts/lib/src/lints/unnecessary_rebuilds_from_media_query.dart
packages/nilts/lib/src/utils/library_element_ext.dart
packages/nilts_test/test/lints/fixed_text_scale_factor_rich_text.dart

Checks if `textScaleFactor` is missing in `RichText` constructor.

feat: fixed_text_scale_factor_rich_text

---

packages/nilts/README.md
packages/nilts/lib/src/lints/defined_void_callback_type.dart
packages/nilts/lib/src/lints/fixed_text_scale_factor_rich_text.dart
packages/nilts/lib/src/lints/flaky_tests_with_set_up_all.dart
packages/nilts/lib/src/lints/unnecessary_rebuilds_from_media_query.dart

Update api docs and problem messages.

docs: update api docs and problem messages

---

packages/nilts/example/example.md

docs: example link

---

.github/workflows/auto-asign.yml

Action for auto assigning PR creator as Assignees.

build: Auto assign

---

packages/nilts/README.md

docs: Badges for readme

---

packages/nilts/lib/src/change_priority.dart

Add notes for priorities of ignore fixes.

docs: notes for ignore fix priority

---

packages/nilts/README.md

Known issues for quick fix priorities.

docs: known issues for quick fix priorities

---

melos.yaml

Fixed version for `melos prepare` command.

build: fixed version for melos prepare

---

.github/workflows/pr-review.yml

PR review with [ai-pr-reviewer](https://github.com/coderabbitai/ai-pr-reviewer).

build: pr review

---

packages/nilts/README.md

docs: update badges link

---

packages/nilts/README.md
packages/nilts/lib/src/lints/defined_void_callback_type.dart
packages/nilts/lib/src/lints/fixed_text_scale_rich_text.dart
packages/nilts/lib/src/lints/flaky_tests_with_set_up_all.dart
packages/nilts/lib/src/lints/no_support_multi_text_direction.dart
packages/nilts/lib/src/lints/shrink_wrapped_scroll_view.dart
packages/nilts/lib/src/lints/unnecessary_rebuilds_from_media_query.dart

docs: format docs

---

pubspec.yaml

Update melos to latest version.

upgrade: melos 3.2.0

---

renovate.json

upgrade: renovate reconfigure

---

.tool-versions

Bump up flutter and dart version.

upgrade: bump up flutter and dart

---

examples/nilts_example/pubspec.lock
examples/nilts_example/pubspec.yaml
packages/nilts/README.md
packages/nilts/pubspec.lock
packages/nilts/pubspec.yaml
packages/nilts_test/pubspec.lock
packages/nilts_test/pubspec.yaml
pubspec.lock
pubspec.yaml

upgrade packages.
- [custom_lint](https://pub.dev/packages/custom_lint/changelog)
- [custom_lint_builder](https://pub.dev/packages/custom_lint_builder/changelog)
- [melos](https://pub.dev/packages/melos/changelog)

upgrade: custom_lint and melos

---

packages/nilts/README.md

docs: replace videos to gifs

---

.tool-versions
examples/nilts_example/android/app/build.gradle
examples/nilts_example/android/gradle/wrapper/gradle-wrapper.properties
examples/nilts_example/android/settings.gradle

Upgrade Android Gradle Plugin and Gradle version in nilts_example.

upgrade: agp and gradle

---

.tool-versions
melos.yaml

Upgrade project flutter sdk version.

upgrade: flutter 3.19.5

---

.github/workflows/build.yml
melos.yaml
pubspec.lock
pubspec.yaml

upgrade melos 5.2.2 and migrate melos.yaml.

upgrade: melos 5.2.2

---

.tool-versions
examples/nilts_example/pubspec.lock
packages/nilts_test/pubspec.lock

Upgrade Flutter and Dart version on development environment.

upgrade: Flutter 3.22, Dart 3.4 on development

---

packages/nilts/pubspec.yaml

docs: funding for pubspec

---

.tool-versions

Upgrade flutter and dart SDK on development.

upgrade: development flutter sdk 3.22.2

---

packages/nilts/README.md
packages/nilts/lib/nilts.dart
packages/nilts/lib/src/change_priority.dart
packages/nilts/lib/src/lints/no_support_web_platform_check.dart
packages/nilts_test/analysis_options.yaml
packages/nilts_test/test/lints/no_support_web_platform_check.dart

Add `no_support_web_platform_check` rule and quick fix.

feat: no_support_web_platform_check

---

.tool-versions
examples/nilts_example/pubspec.lock
examples/nilts_example/pubspec.yaml
melos.yaml
pubspec.lock
pubspec.yaml

- upgrade Flutter and Dart SDK on development
- cleanup development dependencies
- run test with very_good_cli

upgrade: development flutter sdk 3.22.3

---

packages/nilts/lib/src/lints/defined_async_callback_type.dart

Fix _ReplaceWithAsyncCallbackType's replacement introduced #136.

fix: _ReplaceWithAsyncCallbackType replacement

---

packages/nilts/README.md
packages/nilts/lib/nilts.dart
packages/nilts/lib/src/change_priority.dart
packages/nilts/lib/src/lints/defined_async_value_setter_type.dart
packages/nilts_test/test/lints/defined_async_callback_type.dart
packages/nilts_test/test/lints/defined_async_value_setter_type.dart

add `defined_async_value_setter_type` lint rule.

feat: defined_async_value_setter_type

---

packages/nilts/README.md
packages/nilts/lib/nilts.dart
packages/nilts/lib/src/change_priority.dart
packages/nilts/lib/src/lints/defined_async_callback_type.dart
packages/nilts/lib/src/lints/defined_async_value_getter_type.dart
packages/nilts_test/test/lints/defined_async_callback_type.dart
packages/nilts_test/test/lints/defined_async_value_getter_type.dart
packages/nilts_test/test/lints/defined_async_value_setter_type.dart
packages/nilts_test/test/lints/defined_value_getter_type.dart

add defined_async_value_getter_type rule.

feat: defined_async_value_getter_type rule

---

melos.yaml
packages/nilts/lib/src/lints/defined_async_callback_type.dart
packages/nilts/lib/src/lints/defined_async_value_getter_type.dart
packages/nilts/lib/src/lints/defined_async_value_setter_type.dart
packages/nilts/lib/src/lints/defined_value_callback_type.dart
packages/nilts/lib/src/lints/defined_value_getter_type.dart
packages/nilts/lib/src/lints/defined_void_callback_type.dart
packages/nilts_test/test/lints/defined_async_callback_type.dart
packages/nilts_test/test/lints/defined_async_value_getter_type.dart
packages/nilts_test/test/lints/defined_async_value_setter_type.dart
packages/nilts_test/test/lints/defined_value_callback_type.dart
packages/nilts_test/test/lints/defined_value_getter_type.dart
packages/nilts_test/test/lints/defined_void_callback_type.dart

Ignore reporting if evaluated type is instance of alias type.

fix: Ignore alias type

---

.tool-versions
examples/nilts_example/pubspec.lock
examples/nilts_example/pubspec.yaml

- Upgrade Flutter and Dart SDK versions for development

upgrade: flutter 3.24.1

---

.release-please-manifest.json
release-please-config.json

Configuring release-please for path: packages/nilts

chore: bootstrap releases for path: packages/nilts

---

.github/workflows/build.yml
.tool-versions
examples/nilts_example/pubspec.lock
examples/nilts_example/pubspec.yaml
melos.yaml

- upgrade development Flutter and Dart version.

upgrade: flutter 3.24.2

---

.github/workflows/release.yml
release-please-config.json

- Update release-please configs.

build: Update release please configs

---

renovate.json5

- Renovate custom manager for melos.yaml.
https://docs.renovatebot.com/modules/manager/regex/

build: Renovate custom manager for melos.yaml

---

renovate.json5

- Group custom_lint prefix packages update.

build: Group custom_lint renovate update

---

examples/nilts_example/pubspec.yaml
melos.yaml
packages/nilts/pubspec.yaml
packages/nilts_test/pubspec.yaml

- Upgrade custom_lint 0.6.6
- https://pub.dev/packages/custom_lint/changelog

upgrade: custom_lint 0.6.6

---

release-please-config.json

- Update release-please changelog path

build: Update release-please changelog path

---

.github/workflows/release.yml

- Update release.yml workflow name

build: Update release workflow name

---

packages/nilts/CHANGELOG.md

docs: Reformat changelog

---

.tool-versions

- Upgrade Flutter 3.24.3 and Dart 3.5.3 for development.

upgrade: Flutter 3.24.3 for development

---

.tool-versions

- upgrade development flutter and dart versions.

upgrade: flutter 3.24.4

---

examples/nilts_example/pubspec.yaml
packages/nilts/README.md
packages/nilts/pubspec.yaml
packages/nilts_test/pubspec.yaml

upgrade: custom_lint 0.7.0

---

.tool-versions

- upgrade flutter and dart for development

upgrade: flutter 3.27.2, dart 3.6.1

---

.github/workflows/publish.yml
.github/workflows/release.yml

- automate publish
- [Automated publishing of packages to pub.dev | Dart](https://dart.dev/tools/pub/automated-publishing)

build: automate publish

---

.github/workflows/release.yml

- use [actions/create-github-app-token](https://github.com/actions/create-github-app-token)

build: use actions/create-github-app-token

---

CONTRIBUTING.md

- Add details of writing rules for lint rules and quick fixes

docs: Writing rule details

---

.github/PULL_REQUEST_TEMPLATE.md
CONTRIBUTING.md
melos.yaml
packages/nilts/CHANGELOG.md
packages/nilts/README.md
packages/nilts/example/example.md
packages/nilts/lib/src/lints/defined_async_callback_type.dart
packages/nilts/lib/src/lints/defined_async_value_getter_type.dart
packages/nilts/lib/src/lints/defined_async_value_setter_type.dart
packages/nilts/lib/src/lints/defined_value_callback_type.dart
packages/nilts/lib/src/lints/defined_value_getter_type.dart
packages/nilts/lib/src/lints/defined_void_callback_type.dart
packages/nilts/lib/src/lints/fixed_text_scale_rich_text.dart
packages/nilts/lib/src/lints/flaky_tests_with_set_up_all.dart
packages/nilts/lib/src/lints/low_readability_numeric_literals.dart
packages/nilts/lib/src/lints/no_support_multi_text_direction.dart
packages/nilts/lib/src/lints/no_support_web_platform_check.dart
packages/nilts/lib/src/lints/shrink_wrapped_scroll_view.dart
packages/nilts/lib/src/lints/unnecessary_rebuilds_from_media_query.dart
packages/nilts/pubspec.yaml

- transfer owner to @dassssshers from @ronnnnn

docs: transfer owner

---

.tool-versions

- upgrade flutter and dart versions for development

upgrade: fluter 3.27.4, dart 3.6.2

---

.github/workflows/build.yml

- use merge queue to prevent main branch is broken

build: use merge queue

---

packages/nilts/README.md

- update resolved known issues

docs: update resolved known issues

---

melos.yaml

- forget to upgrade custom_lint on melos.yaml 
- #239

upgrade: custom_lint to activate global

---

.github/workflows/pr-title.yml

- check PR title for release note

build: Check PR title

---

packages/nilts_core/.pubignore
packages/nilts_core/CHANGELOG.md

- upgate .pubignore for nilts_core

build: .pubignore for nilts_core

---

release-please-config.json

build: separate release please PR

---

.github/workflows/pr-title.yml
release-please-config.json

- add `release` as commit type

build: add release commit type

---

examples/nilts_example/pubspec.yaml
melos.yaml
packages/nilts/pubspec.yaml
packages/nilts_test/pubspec.yaml

- upgrade custom_lint 0.7.5, custom_lint_builder 0.7.5, analyzer_plugin 0.13.0

upgrade: custom_lint 0.7.5, analyzer_plugin 0.13.0

---

.tool-versions

- upgrade Dart 3.7.2, Flutter 3.29.2

upgrade: update dart to 3.7.2 and flutter to 3.29.2

---

packages/nilts/pubspec.yaml
packages/nilts_flutter_hooks/pubspec.yaml

upgrade: nilts_core 0.2.0

---

.release-please-manifest.json
CHANGELOG.md
LICENSE
README.md
packages/nilts_core/CHANGELOG.md
packages/nilts_flutter_hooks/CHANGELOG.md
release-please-config.json

- prepare release for nilts_flutter_hooks 0.1.0

docs: prepare release for nilts_flutter_hooks 0.1.0

---

.github/workflows/publish.yml

- publish job for nilts_flutter_hooks

build: publish for nilts_flutter_hooks

---

packages/nilts_clock/CHANGELOG.md

- prepare release nilts_clock 0.1.0

release: nilts_clock 0.1.0

---

.github/workflows/publish.yml

build: publish job for nilts_clock

---

.github/workflows/build.yml
.tool-versions
examples/nilts_example/lib/main.dart
examples/nilts_example/pubspec.yaml
packages/nilts_core/lib/src/utils/library_element_ext.dart
pubspec.yaml

- upgrade flutter 3.29.3 for development
- support analyzer 7.4 for nilts_core

upgrade: flutter 3.29.3

---

.tool-versions
analysis_options.yaml
melos.yaml
packages/nilts/lib/src/lints/defined_async_callback_type.dart
packages/nilts/lib/src/lints/defined_async_value_getter_type.dart
packages/nilts/lib/src/lints/defined_async_value_setter_type.dart
packages/nilts/lib/src/lints/defined_value_callback_type.dart
packages/nilts/lib/src/lints/defined_value_getter_type.dart
packages/nilts/lib/src/lints/defined_void_callback_type.dart
packages/nilts/lib/src/lints/fixed_text_scale_rich_text.dart
packages/nilts/lib/src/lints/flaky_tests_with_set_up_all.dart
packages/nilts/lib/src/lints/no_support_multi_text_direction.dart
packages/nilts/lib/src/lints/no_support_web_platform_check.dart
packages/nilts/lib/src/lints/shrink_wrapped_scroll_view.dart
packages/nilts/lib/src/lints/unnecessary_rebuilds_from_media_query.dart
packages/nilts/lib/src/lints/unstable_enum_name.dart
packages/nilts/lib/src/lints/unstable_enum_values.dart
packages/nilts/pubspec.yaml
packages/nilts_clock/lib/src/lints/using_date_time_now.dart
packages/nilts_clock/pubspec.yaml
packages/nilts_core/lib/src/utils/library_element_ext.dart
packages/nilts_core/pubspec.yaml
packages/nilts_flutter_hooks/lib/src/lints/unnecessary_hook_widget.dart
packages/nilts_flutter_hooks/pubspec.yaml
packages/nilts_test/pubspec.yaml
pubspec.yaml

- #337
- #339
- #341
- #342
- ignore deprecated_member_use because of supporting analyzer under 7.4.0

upgrade: upgrade packages

---

packages/nilts/pubspec.yaml
packages/nilts_clock/pubspec.yaml
packages/nilts_flutter_hooks/pubspec.yaml

upgrade: nilts_core 0.3.0

---

packages/nilts/pubspec.yaml
packages/nilts_clock/pubspec.yaml
packages/nilts_core/pubspec.yaml
packages/nilts_flutter_hooks/pubspec.yaml

upgrade: support analyzer 8

---

.tool-versions
examples/nilts_example/pubspec.yaml
packages/nilts/lib/src/lints/defined_async_callback_type.dart
packages/nilts/lib/src/lints/defined_async_value_getter_type.dart
packages/nilts/lib/src/lints/defined_async_value_setter_type.dart
packages/nilts/lib/src/lints/defined_value_callback_type.dart
packages/nilts/lib/src/lints/defined_value_getter_type.dart
packages/nilts/lib/src/lints/defined_void_callback_type.dart
packages/nilts/lib/src/lints/fixed_text_scale_rich_text.dart
packages/nilts/lib/src/lints/flaky_tests_with_set_up_all.dart
packages/nilts/lib/src/lints/low_readability_numeric_literals.dart
packages/nilts/lib/src/lints/no_support_multi_text_direction.dart
packages/nilts/lib/src/lints/no_support_web_platform_check.dart
packages/nilts/lib/src/lints/open_type_hierarchy.dart
packages/nilts/lib/src/lints/shrink_wrapped_scroll_view.dart
packages/nilts/lib/src/lints/unnecessary_rebuilds_from_media_query.dart
packages/nilts/lib/src/lints/unsafe_null_assertion.dart
packages/nilts/lib/src/lints/unstable_enum_name.dart
packages/nilts/lib/src/lints/unstable_enum_values.dart
packages/nilts/pubspec.yaml
packages/nilts_clock/lib/src/lints/using_date_time_now.dart
packages/nilts_clock/pubspec.yaml
packages/nilts_core/lib/src/utils/library_element_ext.dart
packages/nilts_core/pubspec.yaml
packages/nilts_flutter_hooks/lib/src/lints/unnecessary_hook_widget.dart
packages/nilts_flutter_hooks/pubspec.yaml
packages/nilts_test/pubspec.yaml
pubspec.yaml

upgrade!: analyzer 8
